baseURL = 'https://ppcamp.github.io'
languageCode = 'en-us'
theme = "ananke"
themesDir = "./themes"
resourceDir = "./themes/ananke/resources"
staticDir2 = "./static"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 9
googleAnalytics = ""
enableRobotsTXT = true
disqusShortname = "ppcamp"
tags = ["website", "starter", "responsive", "Disqus", "blog", "tech", "programmer", "developer"]
features = ["posts", "shortcodes", "related content", "comments"]
description = "A tech website to share some of my knowledge"
homepage = "https://ppcamp.github.io/"
name = "ppcamp"

[authors]
  name = "ppcamp"
  homepage = "https://www.thenewdynamic.com/"


[taxonomies]
  author = "authors"
  tag = "tags"
  category = "categories"

[languages]
  [languages.en]
    title = "ppcamp"
    weight = 1
    contentDir = "content"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"


[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = 'tango'
    tabWidth = 2

[params]
  authors = ["ppcamp"]
  favicon = "./images/favicon.ico"
  site_logo = ""
  description = "ppcamp's blog"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/ppcamp"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/ppcamp/"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  recent_posts_number = 3
  commentoEnable = false
  custom_css = ["custom.css"]

  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  #background_color_class = "bg-dark-pink"
  #featured_image = "./images/gohugo-default-sample-hero-image.jpg"
