baseURL = 'https://ppcamp.github.io'
languageCode = 'en-us'
theme = "ananke"
themesDir = "./themes"
resourceDir = "./themes/ananke/resources"
staticDir2 = "./static"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 5 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true
disqusShortname = "ppcamp"

[languages]
  [languages.en]
    title = "ppcamp"
    weight = 1
    contentDir = "content"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  author = ""
  favicon = ""
  site_logo = ""
  description = "ppcamp's blog"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/ppcamp"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/ppcamp/"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  #background_color_class = ""
  #featured_image = "./images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 3
  commentoEnable = true
  custom_css = ["custom.css"]